<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE buzon_correos [

<!ELEMENT buzon_correos (cartas, paquetes)>

<!ELEMENT cartas (carta*)>

<!ELEMENT paquetes (paquete*)>

<!ELEMENT carta (#PCDATA)>

<!ELEMENT paquete (#PCDATA)>

]>


<buzon_correos>
	
	<cartas>
	
		<carta>
			
		</carta>
		
		<carta>
			
		</carta>
		
	</cartas>
	
	
	
	<paquetes>
	
		<paquete>
	
		</paquete>
		
		<paquete>
	
		</paquete>
	
	</paquetes>
	

</buzon_correos>
