<?xml version="1.0" encoding="UTF-8" ?>

<!DOCTYPE cd [

	<!ELEMENT cd (songs+, fecha)>
	<!ATTLIST cd titulo CDATA #REQUIRED>

	<!ELEMENT songs (song+)>

	<!ENTITY % name "nombres, apellidos">
	<!ELEMENT nombres (#PCDATA)>
	<!ELEMENT apellidos (#PCDATA)>

	<!ELEMENT song (titulo, compositores, productores, sello, artista) >
		<!ATTLIST song duracion CDATA #REQUIRED
							anio CDATA #REQUIRED >


	<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT compositores (compositor+)>
		<!ELEMENT compositor (nombres, apellidos)>
	<!ELEMENT productores (productor+)>
		<!ELEMENT productor (nombres, apellidos)>
	<!ELEMENT sello (#PCDATA)>
	<!ELEMENT artista (#PCDATA)>
	
	<!ELEMENT fecha EMPTY>
	<!ATTLIST fecha dia CDATA #REQUIRED
					mes CDATA #REQUIRED
					anio CDATA #REQUIRED>

]>

<cd titulo ="Hard Candy">

	<songs>
	
		<song duracion="4:47" anio="2008">
			
			<titulo>Give it 2 me</titulo>
			
			<compositores>
				
				<compositor>		
					<nombres>Pharrell</nombres>
					<apellidos>Williams</apellidos>			
				</compositor>
				
			</compositores>
			
			<productores>	
				<productor>
					<nombres>Pharrell</nombres>
					<apellidos>Williams</apellidos>	
				</productor>
			</productores>
			
			<sello>
				Warner Bros. Records
			</sello>
			
			<artista>
				Maddona
			</artista>	
	
		</song>
	
	</songs>
	
	<fecha dia="19" mes="04" anio="2008"/>

</cd>