<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE liga[
<!ELEMENT liga (partido*)>
<!ELEMENT partido (equipoLocal, equipoVisitante)>
<!ELEMENT equipoLocal (#PCDATA)>
<!ELEMENT equipoVisitante (#PCDATA)>

<!ATTLIST equipoLocal goles CDATA #REQUIRED>
<!ATTLIST equipoVisitante goles CDATA #REQUIRED>

]>

<liga>
	<partido>
		
		<equipoLocal goles="0">Nottingham Presa</equipoLocal>
		
		<equipoVisitante goles="1">Inter de Mitente</equipoVisitante>
		
	</partido>
	
	<partido>
		
		<equipoLocal goles="3">Vodka Juniors</equipoLocal>
		
		<equipoVisitante goles="3">Sparta da Risa</equipoVisitante>
		
	</partido>
	
	<partido>
		
		<equipoLocal goles="4">Water de Munich</equipoLocal>
		
		<equipoVisitante goles="2">Esteaua es del grifo</equipoVisitante>
		
	</partido>
	
	
</liga>
